version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./rori:/var/www
    ports:
      - "8080:80"
    links:
      - php
  php:
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:
      - ./rori:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
  mysql:
    image: mysql:5.6
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
  phpmyadmin:
    build:
      context: ./
      dockerfile: phpmyadmin.dockerfile
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 3360:3360
    volumes:
     - /sessions
volumes:
  mysqldata:
